services:
  neo4j:
    image: neo4j:5.12.0
    container_name: graphrag-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      # Minimal memory settings for Azure VM stability
      - NEO4J_dbms_memory_heap_initial__size=128m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_dbms_memory_pagecache_size=128m
      # Basic configuration only
      - NEO4J_dbms_default_listen_address=0.0.0.0

  api:
    build: .
    container_name: graphrag-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}

volumes:
  neo4j_data: